network.host: 0.0.0.0

cluster.name: elasticsearch
cluster.initial_master_nodes: node1

node.master: true
node.name: node1

path.logs: L:/
path.data: D:/

discovery.seed_hosts: 127.0.0.1, [::1]
http.port: 9200
