# the base image
FROM mcr.microsoft.com/windows/servercore:1903

# create two volumes
VOLUME c:/Data
VOLUME c:/Logs

# create two drives L:\ => C:\Logs and D:\ => C:\Data
SHELL ["powershell.exe", "-Command"]

RUN Set-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\DOS Devices' -Name 'L:' -Value '\??\C:\Logs' -Type String;

RUN Set-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\DOS Devices' -Name 'D:' -Value '\??\C:\Data' -Type String;

LABEL maintainer="vndevpro@gmail.com"
