version: '3'
services:
    elasticsearch:
        ports:
            - "9200:9200"
            - "9300:9300"
        image: "mydockercity/elasticsearchservercore:latest"
    kibana:
        ports:
            - "5601:5601"
        image: "mydockercity/kibanaservercore:latest"
    filebeat:
        image: "mydockercity/filebeatservercore:latest"
